load("//build_tools/bazel:defs.bzl", "loom_test_library")
load("//target/amdgpu:profile.bzl", "AMDGPU_HARDWARE")

package(default_visibility = ["//visibility:public"])

loom_test_library(
    name = "q4_k",
    srcs = ["q4_k.loom"],
    compile_targets = ["//target/amdgpu:gfx11_generic"],
    deps = ["//motif/format/ggml:q4_k"],
    execution_profiles = [AMDGPU_HARDWARE],
)

loom_test_library(
    name = "q5_k",
    srcs = ["q5_k.loom"],
    compile_targets = ["//target/amdgpu:gfx11_generic"],
    deps = ["//motif/format/ggml:q5_k"],
    execution_profiles = [AMDGPU_HARDWARE],
)

loom_test_library(
    name = "q6_k",
    srcs = ["q6_k.loom"],
    compile_targets = ["//target/amdgpu:gfx11_generic"],
    deps = ["//motif/format/ggml:q6_k"],
    execution_profiles = [AMDGPU_HARDWARE],
)
