load("@iree//build_tools/bazel:python.bzl", "iree_py_test")

package(default_visibility = ["//visibility:public"])

iree_py_test(
    name = "compile_report_test",
    srcs = [
        "build_tools/compile_report.py",
        "build_tools/compile_report_test.py",
    ],
    main = "build_tools/compile_report_test.py",
)

iree_py_test(
    name = "dev_test",
    srcs = [
        "build_tools/benchmark_sweep.py",
        "dev.py",
        "dev_test.py",
    ],
    main = "dev_test.py",
)
