#!/usr/bin/env python3
# Copyright 2026 AMD ROCm™ Software
# SPDX-License-Identifier: MIT

"""Repository maintenance entry point for the Loom kernel library."""

from __future__ import annotations

import argparse
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent
LOCAL_BAZELRC = REPOSITORY_ROOT / ".bazelrc.local"
LOOM_FORMAT_TARGET = "@iree//loom/src/loom/tools/loom-format"
LOOM_SOURCE_ROOTS = ("kernel", "model", "motif", "target")


class UserError(Exception):
    """Reports a command-line or local-environment problem."""


def _bazel_executable() -> str:
    executable = shutil.which("bazelisk") or shutil.which("bazel")
    if executable is None:
        raise UserError("Bazelisk or Bazel must be available on PATH")
    return executable


def _run(command: list[str], *, capture_output: bool = False) -> str:
    print("+ " + shlex.join(command), flush=True)
    result = subprocess.run(
        command,
        capture_output=capture_output,
        check=False,
        cwd=REPOSITORY_ROOT,
        text=True,
    )
    if result.returncode != 0:
        if capture_output:
            sys.stdout.write(result.stdout)
            sys.stderr.write(result.stderr)
        raise subprocess.CalledProcessError(result.returncode, command)
    return result.stdout if capture_output else ""


def _bazel(arguments: list[str], *, capture_output: bool = False) -> str:
    return _run([_bazel_executable(), *arguments], capture_output=capture_output)


def _write_source_override(source_path: str) -> None:
    source_root = Path(source_path).expanduser().resolve()
    if not (source_root / "MODULE.bazel").is_file():
        raise UserError(f"Loom source module has no MODULE.bazel: {source_root}")
    override_argument = f"--override_module=iree={source_root}"
    contents = (
        "# Generated by dev.py setup --loom-source.\n"
        f"common {shlex.quote(override_argument)}\n"
    )
    if LOCAL_BAZELRC.exists() and LOCAL_BAZELRC.read_text() == contents:
        print(f"Local Loom source already selected: {source_root}", flush=True)
        return
    LOCAL_BAZELRC.write_text(contents)
    print(f"Selected local Loom source: {source_root}", flush=True)


def _select_release() -> None:
    if LOCAL_BAZELRC.exists():
        LOCAL_BAZELRC.unlink()
        print("Selected the Loom revision pinned by MODULE.bazel", flush=True)
    else:
        print(
            "The Loom revision pinned by MODULE.bazel is already selected",
            flush=True,
        )


def _bazel_arguments(arguments: list[str]) -> list[str]:
    if arguments and arguments[0] == "--":
        return arguments[1:]
    return arguments


def _setup(args: argparse.Namespace) -> None:
    if args.loom_source:
        _write_source_override(args.loom_source)
    elif args.release:
        _select_release()
    _bazel(["build", "--nobuild", "--lockfile_mode=update", "//..."])


def _build(args: argparse.Namespace) -> None:
    _bazel(["build", *_bazel_arguments(args.bazel_args), "//..."])


def _test(args: argparse.Namespace) -> None:
    _bazel(["test", *_bazel_arguments(args.bazel_args), "//..."])


def _loom_sources(arguments: list[str]) -> list[Path]:
    if arguments:
        sources = [(REPOSITORY_ROOT / path).resolve() for path in arguments]
    else:
        sources = []
        for relative_root in LOOM_SOURCE_ROOTS:
            source_root = REPOSITORY_ROOT / relative_root
            if source_root.is_dir():
                sources.extend(source_root.rglob("*.loom"))
    invalid_sources = [path for path in sources if not path.is_file()]
    if invalid_sources:
        raise UserError(f"Loom source does not exist: {invalid_sources[0]}")
    return sorted(set(sources))


def _resolve_loom_format() -> Path:
    _bazel(["build", LOOM_FORMAT_TARGET])
    output = _bazel(
        ["cquery", LOOM_FORMAT_TARGET, "--output=files"],
        capture_output=True,
    )
    output_paths = [line.strip() for line in output.splitlines() if line.strip()]
    if len(output_paths) != 1:
        raise UserError(f"Expected one loom-format output, found {len(output_paths)}")
    execution_root = Path(
        _bazel(["info", "execution_root"], capture_output=True).strip()
    )
    executable = execution_root / output_paths[0]
    if not executable.is_file():
        raise UserError(f"Built loom-format output does not exist: {executable}")
    return executable


def _format(args: argparse.Namespace) -> None:
    sources = _loom_sources(args.sources)
    formatter = _resolve_loom_format()
    for source in sources:
        _run(
            [
                str(formatter),
                str(source),
                "--to=text",
                f"--output={source}",
            ]
        )
    print(f"Formatted {len(sources)} Loom source files", flush=True)


def _create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup_parser = subparsers.add_parser(
        "setup",
        help="Resolve the pinned revision or select a local Loom source tree.",
    )
    setup_mode = setup_parser.add_mutually_exclusive_group()
    setup_mode.add_argument(
        "--loom-source",
        metavar="PATH",
        help="Use an uncommitted local HRX checkout as the Loom module.",
    )
    setup_mode.add_argument(
        "--release",
        action="store_true",
        help="Return to the Loom revision pinned by MODULE.bazel.",
    )
    setup_parser.set_defaults(handler=_setup)

    build_parser = subparsers.add_parser(
        "build",
        help="Build every library and target-qualified artifact.",
    )
    build_parser.add_argument("bazel_args", nargs=argparse.REMAINDER)
    build_parser.set_defaults(handler=_build)

    test_parser = subparsers.add_parser(
        "test",
        help="Run format, planning, and compilation policy checks.",
    )
    test_parser.add_argument("bazel_args", nargs=argparse.REMAINDER)
    test_parser.set_defaults(handler=_test)

    format_parser = subparsers.add_parser(
        "format",
        help="Canonically format all Loom sources or the named files.",
    )
    format_parser.add_argument("sources", nargs="*")
    format_parser.set_defaults(handler=_format)

    return parser


def main() -> int:
    parser = _create_parser()
    args = parser.parse_args()
    try:
        args.handler(args)
    except UserError as error:
        parser.error(str(error))
    except subprocess.CalledProcessError as error:
        return error.returncode
    return 0


if __name__ == "__main__":
    sys.exit(main())
