#!/usr/bin/env python3
# Copyright 2026 AMD ROCm™ Software
# SPDX-License-Identifier: MIT

"""Repository maintenance entry point for the Loom kernel library."""

from __future__ import annotations

import argparse
import shlex
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath


REPOSITORY_ROOT = Path(__file__).resolve().parent
LOCAL_BAZELRC = REPOSITORY_ROOT / ".bazelrc.local"
LOOM_FORMAT_TARGET = "@iree//loom/src/loom/tools/loom-format"
LOOM_SOURCE_ROOTS = ("kernel", "model", "motif", "target")
SOURCE_POLICY_TOOL = REPOSITORY_ROOT / "build_tools" / "bazel" / "source_policy.py"


class UserError(Exception):
    """Reports a command-line or local-environment problem."""


def _bazel_executable() -> str:
    executable = shutil.which("bazelisk") or shutil.which("bazel")
    if executable is None:
        raise UserError("Bazelisk or Bazel must be available on PATH")
    return executable


def _run(command: list[str], *, capture_output: bool = False) -> str:
    print("+ " + shlex.join(command), flush=True)
    result = subprocess.run(
        command,
        capture_output=capture_output,
        check=False,
        cwd=REPOSITORY_ROOT,
        text=True,
    )
    if result.returncode != 0:
        if capture_output:
            sys.stdout.write(result.stdout)
            sys.stderr.write(result.stderr)
        raise subprocess.CalledProcessError(result.returncode, command)
    return result.stdout if capture_output else ""


def _bazel(arguments: list[str], *, capture_output: bool = False) -> str:
    return _run([_bazel_executable(), *arguments], capture_output=capture_output)


def _write_source_override(source_path: str) -> None:
    source_root = Path(source_path).expanduser().resolve()
    if not (source_root / "MODULE.bazel").is_file():
        raise UserError(f"Loom source module has no MODULE.bazel: {source_root}")
    override_argument = f"--override_module=iree={source_root}"
    contents = (
        "# Generated by dev.py setup --loom-source.\n"
        f"common {shlex.quote(override_argument)}\n"
    )
    if LOCAL_BAZELRC.exists() and LOCAL_BAZELRC.read_text() == contents:
        print(f"Local Loom source already selected: {source_root}", flush=True)
        return
    LOCAL_BAZELRC.write_text(contents)
    print(f"Selected local Loom source: {source_root}", flush=True)


def _select_release() -> None:
    if LOCAL_BAZELRC.exists():
        LOCAL_BAZELRC.unlink()
        print("Selected the Loom revision pinned by MODULE.bazel", flush=True)
    else:
        print(
            "The Loom revision pinned by MODULE.bazel is already selected",
            flush=True,
        )


def _bazel_arguments(arguments: list[str]) -> list[str]:
    if arguments and arguments[0] == "--":
        return arguments[1:]
    return arguments


def _setup(args: argparse.Namespace) -> None:
    if args.loom_source:
        _write_source_override(args.loom_source)
    elif args.release:
        _select_release()
    _bazel(["build", "--nobuild", "--lockfile_mode=update", "//..."])


def _lint_repository() -> None:
    _run(
        [
            sys.executable,
            "-B",
            str(SOURCE_POLICY_TOOL),
            f"--repository-root={REPOSITORY_ROOT}",
        ]
    )


def _build(args: argparse.Namespace) -> None:
    _lint_repository()
    _bazel(["build", *_bazel_arguments(args.bazel_args), "//..."])


def _test(args: argparse.Namespace) -> None:
    _lint_repository()
    _bazel(["test", *_bazel_arguments(args.bazel_args), "//..."])


def _lint(args: argparse.Namespace) -> None:
    del args
    _lint_repository()


def _is_loom_source_path(path: str) -> bool:
    source_path = PurePosixPath(path)
    return (
        "\\" not in path
        and source_path.as_posix() == path
        and not source_path.is_absolute()
        and ".." not in source_path.parts
        and source_path.suffix == ".loom"
        and bool(source_path.parts)
        and source_path.parts[0] in LOOM_SOURCE_ROOTS
    )


def _normalize_loom_source(argument: str | Path) -> Path:
    source = Path(argument).expanduser()
    if not source.is_absolute():
        source = REPOSITORY_ROOT / source
    source = source.resolve()
    try:
        relative_source = source.relative_to(REPOSITORY_ROOT.resolve()).as_posix()
    except ValueError as error:
        raise UserError(f"Loom source is outside the repository: {source}") from error
    if not _is_loom_source_path(relative_source):
        raise UserError(
            "Loom sources must be .loom files below kernel/, model/, motif/, "
            f"or target/: {relative_source}"
        )
    if not source.is_file():
        raise UserError(f"Loom source does not exist: {source}")
    return source


def _loom_sources(arguments: list[str]) -> list[Path]:
    if arguments:
        sources = [_normalize_loom_source(path) for path in arguments]
    else:
        sources = []
        for relative_root in LOOM_SOURCE_ROOTS:
            source_root = REPOSITORY_ROOT / relative_root
            if source_root.is_dir():
                sources.extend(
                    _normalize_loom_source(path) for path in source_root.rglob("*.loom")
                )
    return sorted(set(sources))


def _source_relative_path(source: Path) -> str:
    return source.relative_to(REPOSITORY_ROOT.resolve()).as_posix()


def _staged_loom_sources() -> list[Path]:
    output = _run(
        [
            "git",
            "--literal-pathspecs",
            "diff",
            "--cached",
            "--name-only",
            "--diff-filter=ACMR",
            "-z",
            "--",
            *LOOM_SOURCE_ROOTS,
        ],
        capture_output=True,
    )
    sources = []
    for path in output.split("\0"):
        if not path or not _is_loom_source_path(path):
            continue
        source = (REPOSITORY_ROOT / path).resolve()
        if source.is_file():
            sources.append(_normalize_loom_source(source))
    return sorted(set(sources))


def _unstaged_loom_sources(sources: list[Path]) -> list[str]:
    if not sources:
        return []
    relative_sources = [_source_relative_path(source) for source in sources]
    output = _run(
        [
            "git",
            "--literal-pathspecs",
            "diff",
            "--no-ext-diff",
            "--name-only",
            "-z",
            "--",
            *relative_sources,
        ],
        capture_output=True,
    )
    return sorted(path for path in output.split("\0") if path)


def _stage_loom_sources(sources: list[Path]) -> None:
    if not sources:
        return
    _run(
        [
            "git",
            "--literal-pathspecs",
            "add",
            "--",
            *[_source_relative_path(source) for source in sources],
        ]
    )


def _run_loom_format(mode: str, sources: list[Path]) -> None:
    _bazel(
        [
            "run",
            LOOM_FORMAT_TARGET,
            "--",
            mode,
            *[str(source) for source in sources],
        ]
    )


def _format(args: argparse.Namespace) -> None:
    if args.staged and args.sources:
        raise UserError("--staged cannot be combined with explicit source paths")
    sources = _staged_loom_sources() if args.staged else _loom_sources(args.sources)
    if not sources:
        selection = "staged " if args.staged else ""
        print(f"No {selection}Loom source files to format", flush=True)
        return
    if args.staged and args.mode == "fix":
        unstaged_sources = _unstaged_loom_sources(sources)
        if unstaged_sources:
            rendered_sources = ", ".join(unstaged_sources)
            raise UserError(
                "Cannot format partially staged Loom sources without staging "
                f"uncommitted hunks: {rendered_sources}"
            )

    if args.mode == "check":
        _run_loom_format("--check", sources)
        print(f"Checked {len(sources)} Loom source files", flush=True)
        return

    _run_loom_format("--in-place", sources)
    if args.staged:
        _stage_loom_sources(sources)
    _run_loom_format("--check", sources)
    print(f"Formatted and checked {len(sources)} Loom source files", flush=True)


def _hook(args: argparse.Namespace) -> None:
    del args
    lefthook = shutil.which("lefthook")
    if lefthook is None:
        raise UserError("Lefthook must be available on PATH")
    _run([lefthook, "install"])


def _create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup_parser = subparsers.add_parser(
        "setup",
        help="Resolve the pinned revision or select a local Loom source tree.",
    )
    setup_mode = setup_parser.add_mutually_exclusive_group()
    setup_mode.add_argument(
        "--loom-source",
        metavar="PATH",
        help="Use an uncommitted local HRX checkout as the Loom module.",
    )
    setup_mode.add_argument(
        "--release",
        action="store_true",
        help="Return to the Loom revision pinned by MODULE.bazel.",
    )
    setup_parser.set_defaults(handler=_setup)

    build_parser = subparsers.add_parser(
        "build",
        help="Build every library and target-qualified artifact.",
    )
    build_parser.add_argument("bazel_args", nargs=argparse.REMAINDER)
    build_parser.set_defaults(handler=_build)

    test_parser = subparsers.add_parser(
        "test",
        help="Run format, planning, and compilation policy checks.",
    )
    test_parser.add_argument("bazel_args", nargs=argparse.REMAINDER)
    test_parser.set_defaults(handler=_test)

    lint_parser = subparsers.add_parser(
        "lint",
        help="Check repository architecture and dependency policy.",
    )
    lint_parser.set_defaults(handler=_lint)

    format_parser = subparsers.add_parser(
        "format",
        help="Check or fix canonical formatting for selected Loom sources.",
    )
    format_mode = format_parser.add_mutually_exclusive_group()
    format_mode.add_argument(
        "--check",
        action="store_const",
        const="check",
        dest="mode",
        help="Check canonical formatting without changing files.",
    )
    format_mode.add_argument(
        "--fix",
        action="store_const",
        const="fix",
        dest="mode",
        help="Rewrite noncanonical files and verify the result (default).",
    )
    format_parser.add_argument(
        "--staged",
        action="store_true",
        help="Select staged .loom files and restage canonical rewrites.",
    )
    format_parser.add_argument("sources", nargs="*")
    format_parser.set_defaults(handler=_format, mode="fix")

    hook_parser = subparsers.add_parser(
        "hook",
        help="Install the repository's staged-source pre-commit hook.",
    )
    hook_parser.set_defaults(handler=_hook)

    return parser


def main() -> int:
    parser = _create_parser()
    args = parser.parse_args()
    try:
        args.handler(args)
    except UserError as error:
        parser.error(str(error))
    except subprocess.CalledProcessError as error:
        return error.returncode
    return 0


if __name__ == "__main__":
    sys.exit(main())
