# Copyright 2026 AMD ROCm™ Software
# SPDX-License-Identifier: MIT

"""Selects the pinned or a local Loom compiler source tree."""

from __future__ import annotations

import argparse
import shlex
from pathlib import Path
from typing import Any

from ..context import RepositoryContext, UserError


def _write_source_override(context: RepositoryContext, source_path: str) -> None:
    source_root = Path(source_path).expanduser()
    if not source_root.is_absolute():
        source_root = context.repository_root / source_root
    source_root = source_root.resolve()
    if not (source_root / "MODULE.bazel").is_file():
        raise UserError(f"Loom source module has no MODULE.bazel: {source_root}")
    override_argument = f"--override_module=iree={source_root.as_posix()}"
    contents = (
        "# Generated by dev.py setup --loom-source.\n"
        f"common {shlex.quote(override_argument)}\n"
    )
    local_bazelrc = context.repository_root / ".bazelrc.local"
    if local_bazelrc.exists() and local_bazelrc.read_text(encoding="utf-8") == contents:
        print(f"Local Loom source already selected: {source_root}", flush=True)
        return
    local_bazelrc.write_text(contents, encoding="utf-8")
    print(f"Selected local Loom source: {source_root}", flush=True)


def _select_release(context: RepositoryContext) -> None:
    local_bazelrc = context.repository_root / ".bazelrc.local"
    if local_bazelrc.exists():
        local_bazelrc.unlink()
        print("Selected the Loom revision pinned by MODULE.bazel", flush=True)
    else:
        print(
            "The Loom revision pinned by MODULE.bazel is already selected",
            flush=True,
        )


def _run(args: argparse.Namespace, context: RepositoryContext) -> None:
    if args.loom_source:
        _write_source_override(context, args.loom_source)
    elif args.release:
        _select_release(context)
    context.bazel(["build", "--nobuild", "--lockfile_mode=update", "//..."])


def register(subparsers: Any) -> None:
    parser = subparsers.add_parser(
        "setup",
        help="Resolve the pinned revision or select a local Loom source tree.",
        description=__doc__,
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--loom-source",
        metavar="PATH",
        help="Use an uncommitted local HRX checkout as the Loom module.",
    )
    mode.add_argument(
        "--release",
        action="store_true",
        help="Return to the Loom revision pinned by MODULE.bazel.",
    )
    parser.set_defaults(handler=_run)
