# Copyright 2026 AMD ROCm™ Software
# SPDX-License-Identifier: MIT

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux_bazel:
    name: Linux / Bazel / Source Loom
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    container:
      image: ghcr.io/rocm/no_rocm_image_ubuntu24_04@sha256:4150afe4759d14822f0e3f8930e1124f26e11f68b5c7b91ec9a02b20b1ebbb98
    env:
      AR: ar
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Adjust git config
        run: git config --global --add safe.directory "$PWD"

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # v0.19.0
        with:
          bazelisk-cache: true
          bazelisk-version: "1.29.0"
          cache-save: ${{ github.event_name == 'push' }}
          repository-cache: true

      - name: Test libraries with source-built Loom tools
        run: python dev.py test
